package com.kanomiya.hinaoutlineprocessor.assets.menudoc;

/**
 * Created by Kanomiya in 2017/02.
 */
public enum WhenEnabled {
    ALWAYS,
    ALWAYS_DISABLED,
    WHEN_DOCUMENT_LOADED,

    WHEN_VIEW_MODE,
    UNLESS_VIEW_MODE,
    WHEN_EDIT_MODE,
    UNLESS_EDIT_MODE,

    WHEN_FILE_LOADED,
    WHEN_NODE_SELECTED,
    WHEN_ABOVE_SELECTED_EXISTS,
    WHEN_BELOW_SELECTED_EXISTS,
    UNLESS_SELECTED_IS_LAST_ONE,

    WHEN_TREE_PANE_FOCUSED,
    UNLESS_TREE_PANE_FOCUSED,
    WHEN_TEXT_PANE_FOCUSED,
    WHEN_TITLE_PANE_FOCUSED,
    UNLESS_TITLE_PANE_FOCUSED,
    WHEN_BODY_PANE_FOCUSED,
    UNLESS_BODY_PANE_FOCUSED,

    WHEN_UNDOABLE,
    WHEN_REDOABLE,

    ;

}
